language: node_js
before_script:
  - npm install -g codeclimate-test-reporter
node_js:
  - "6"
  - "7"
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - coveralls < coverage/lcov.info
